---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: api
spec:
  protocol: http

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api
spec:
  destination:
    name: api
  sources:
    - name: ingress-gateway
      action: allow

---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: metrics
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: metrics # prom scraping port
      protocol: TCP
      port: 20200
      targetPort: 20200

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api_v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        metrics: enabled
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service-upstreams: 'payments:9091'
        #consul.hashicorp.com/transparent-proxy: 'true'
        #consul.hashicorp.com/transparent-proxy-overwrite-probes: 'true'
        #consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: '9090'
    spec:  
      serviceAccountName: api
      automountServiceAccountToken: true
      containers:
        - name: api
          image: nicholasjackson/canary-api:0.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: "PAYMENTS"
              value: "http://localhost:9091"
            - name: "WEATHER"
              value: "http://localhost:9091/WeatherForecast"
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            periodSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 5
            initialDelaySeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"