---
apiVersion: v1
kind: Service
metadata:
  name: git
spec:
  selector:
    app: git
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git
  labels:
    app: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git
  template:
    metadata:
      labels:
        app: git
    spec:
      containers:
      - name: git
        image: hashicraft/gogs:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        - containerPort: 22