FROM hashicorp/waypoint-odr:latest
SHELL ["/kaniko/bin/sh", "-c"]

ENV HOME /root
ENV USER root
ENV PATH="${PATH}:/kaniko"
ENV SSL_CERT_DIR=/kaniko/ssl/certs
ENV DOCKER_CONFIG /kaniko/.docker/
ENV XDG_CONFIG_HOME=/kaniko/.config/

COPY ./registry.cert  /kaniko/ssl/certs/registry.pem
RUN cat /kaniko/ssl/certs/registry.pem >> /kaniko/ssl/certs/ca-certificates.crt

RUN wget https://github.com/hashicorp-dev-advocates/waypoint-plugin-noop/releases/download/v0.2.0/waypoint-plugin-noop_linux_amd64.zip && \
    unzip waypoint-plugin-noop_linux_amd64.zip
RUN mkdir -p /kaniko/.config/waypoint/plugins/
RUN cp waypoint-plugin-noop /kaniko/.config/waypoint/plugins/waypoint-plugin-noop